---
title: "On Rectangular Map Approximations"
author: "Christian Panse"
date: "`r Sys.Date()`"
bibliography:
  - recmap.bib
csl: ieee.csl
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{recmap primer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Intro

This package contains a C++ implementation of the recmap algorithm 
[[@recmap]](http://dx.doi.org/10.1109/INFVIS.2004.57).
The input contains for each map region 

- a tuple of (x, y) values corresponding to the (longitude, latitude) position 
- a map ratio, 
- and a statistical value z.

The (x, y) coordinates represents the center of the minimal bounding boxes (MBB), 
the ratio the longitude / latitude 
ratios, and the  statistical values define the desired 
area of each map region. 

The output is a rectangular cartogram where the map regions are 

- non overlapping, 
- connected, 
- ratio and area of each rectangle corresponds to the desired areas.
- rectangles are parallel to the axes

The construction heuristic places the rectangles in a way that important 
spatial constraints, in particular

- the topology of the pseudo dual graph,
- the relative position of MBB centers, 
- and the ratios of each input map regions.

are tried to be preserved


```{r fig.width=7, fig.retina=2, fig.cap="Rectangular Cartogram of the U.S. election 2004; The area corresponds to the number of electors. The graphic was composed using the original implementation of the construction heuristic RecMap MP2 introduced in [@recmap]."}

library(recmap)
op<-par(mar=c(0,0,0,0), bg='black')
recmap:::.draw_recmap_us_state_ev(asp = 1, xlab='', ylab='', axes=FALSE)
```

#References
