# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_angle <- function(x0, y0, x1, y1) {
    .Call('recmap_get_angle', PACKAGE = 'recmap', x0, y0, x1, y1)
}

recmap <- function(df) {
    .Call('recmap_recmap', PACKAGE = 'recmap', df)
}

